kind: ConfigMap
apiVersion: v1
metadata:
    name: {{ .Chart.Name }}-config
    namespace: {{ .Release.Namespace }}
data:
{{- range  $val := toStrings .Values.app.config }}
  config.yaml: |
{{ $val | indent 4}}
{{- end }}
