---

scaler:
  scale_up_interval: 30
  scale_down_interval: 30
selenium:
  url: "http://localhost:4444"
kubernetes:
  api_url: "https://kubernetes.default.svc.cluster.local"
  auth_token_path: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  ca_cert_path: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
deployments:
  default-deployment:
    api_version: "apps/v1"
    namespace: "default"
    stereotype_selector: "browserName"
    stereotype_selector_value: "chrome"
    min_replicas: 1
    max_replicas: 2
    scale_up_step: 1
    scale_down_step: 1
    scale_up_threshold: 1.0
    scale_down_threshold: 0.7
