# Default values for selenium-grid-k8s-scaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Replica count of the selenium-grid-k8s-scaler pod
replicaCount: 1
image:
  # -- Image repository
  repository: "imatviian/selenium-grid-k8s-scaler"
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion
  tag: ""

# -- base64 encoded image registry secret
dockerconfigjson: ""
# -- Use this only if you dont want to use dockerconfig secret
imagePullSecrets: []
#  - name: my-imagepullsecret
# -- Replaces the name of the chart in the Chart.yaml file
nameOverride: ""
# -- Completely replaces the generated name
fullnameOverride: ""

# -- App sepecific vars
app:
  # -- Path to the application PID file relatively to the app working directory
  pidFilePath: scaler.pid
  # -- Application log level: debug|info|warning|error
  logLevel: info
  config: |
    scaler:
      scale_up_interval: 30
      scale_down_interval: 30
    selenium:
      url: "http://localhost:4444"
    kubernetes:
      api_url: "https://kubernetes.default.svc.cluster.local"
      auth_token_path: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      ca_cert_path: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    deployments:
      default-deployment:
        api_version: "apps/v1"
        namespace: "default"
        stereotype_selector: "browserName"
        stereotype_selector_value: "chrome"
        min_replicas: 1
        max_replicas: 2
        scaling_step: 1
        scale_up_threshold: 1.0
        scale_down_threshold: 0.7
  # -- Environment variables
  env: []
  # env:
  # - name: FOO
  #   value: "bar"
  # -- Environment variables created from external Kubernetes Secret
  envSecrets: []
  # - name: my-secret
  #   valueFrom:
  #     secretKeyRef:
  #       key: foo
  #       name: bar

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- Name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: "selenium-grid-scaler-sa"

rbac:
  # -- Enable/Disable RBAC
  enabled: true

# -- Specific pod annotations
podAnnotations: {}
securityContext:
  # -- Allow or not allow to run application as root user
  runAsNonRoot: true
  # -- Run as specified UID (nobody is reccomended default)
  runAsUser: 65534
  # -- Run as specified GID (nogroup is reccomended default)
  runAsGroup: 65534

resources:
  limits:
    # -- CPU hard limit
    cpu: 100m
    # -- Memory hard limit
    memory: 128Mi
  requests:
    # -- Requests cpu value
    cpu: 100m
    # -- Requests memory value
    memory: 64Mi

# -- Specific node selectors
nodeSelector: {}
# -- Specific toleration options
tolerations: []
# -- Specific affinity options
affinity: {}
