---

name: ci

on:
  push:
    branches:
      - main
    paths:
      - scaler/**

env:
  image_repo: imatviian/selenium-grid-k8s-scaler
  ver_major: 1
  ver_minor: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.image_repo }}:${{ env.ver_major }}.${{ env.ver_minor }}.${{ github.run_number }}
